theme: jekyll-theme-merlot
title: Naomi Deokule

description: A current highschool student at The Bishop’s School in La Jolla, CA   

                                        Class of 2021
                                
