theme: jekyll-theme-merlot
title: Naomi Deokule


description: A current highschool ('21) student at The Bishop’s School in La Jolla, CA   

                                        
                                
